WIP: cobra and viper support for non interactive use
naggie/dsnet pull request #40
Opened 2020-12-31 09:30 UTC by xsteadfastx

This PR is the plan to include cobra and viper to dsnet for abilities for non-interactive use like suggested in #17

2020-12-31 12:38 UTC, xsteadfastx commented
this would be just a beginning. next thing would be adding flags for the things the prompt asks for.

2020-12-31 18:46 UTC, botto commented
Excellent, this looks great.

Not as part of this PR but what would you think of maybe using viper to handle the config in general, as it supports other formats too?

2021-01-02 10:26 UTC, xsteadfastx commented
> Excellent, this looks great.
> 
> Not as part of this PR but what would you think of maybe using viper to handle the config in general, as it supports other formats too?

yes this would be great... in the init command we could add a flag for the config file format you want to have... json standard and yaml/toml as option.

2021-01-02 11:07 UTC, naggie commented
Thanks @xsteadfastx -- will review and test this as soon as I can. Cobra/viper seems to be the library to use.

Regarding supporting toml or other configuration file support; this isn't an option as the configuration file (well, database) is edited programmatically so comments can't be retained.

2021-01-02 11:12 UTC, xsteadfastx commented
> Thanks

i never used this but viper also supports writing config files... so there is a chance to support multiple formats: https://github.com/spf13/viper#writing-config-files

but this is just... a niche feature :) 

i hope my PR is ok and that you find it useful. thank you for this wonderful piece of software... making everything a little easier!

2021-01-03 21:43 UTC, xsteadfastx commented
Btw, just tested it in a productive environment for myself and i could add all the new peers in a scripted way, with success!

2021-01-27 17:04 UTC, naggie commented
note for myself -- check out https://github.com/AlecAivazis/survey for the interactive stuff.

Sorry @xsteadfastx still haven't got round to reviewing. Will do in the next week hopefully

2021-01-28 11:41 UTC, xsteadfastx commented
no problem :) i just can say we use my PR fork here in production... generating alot of client configs on the fly through ansible... without any problems so far :)

2021-01-31 09:53 UTC, botto commented
> no problem :) i just can say we use my PR fork here in production... generating alot of client configs on the fly through ansible... without any problems so far :)

That's very encouraging. Nice to hear it's a useful tool

2021-01-31 10:02 UTC, botto requested changes

2021-01-31 10:02 UTC, botto commented on add.go
> +		ExitFail("Unrecognised OUTPUT type")
This should still print DSNET_OUTPUT per the env prefix in the viper conf

2021-01-31 12:22 UTC, botto commented
Hey @xsteadfastx  I created a PR with some suggestions against your branch https://github.com/xsteadfastx/dsnet/pull/1

I think we probably want to keep the CLI interface backwards compatible and not have the usage confusing when using the CLI as a human and not a script

2021-02-01 08:04 UTC, xsteadfastx commented
> Hey @xsteadfastx I created a PR with some suggestions against your branch [xsteadfastx#1](https://github.com/xsteadfastx/dsnet/pull/1)
> 
> I think we probably want to keep the CLI interface backwards compatible and not have the usage confusing when using the CLI as a human and not a script

yes this is a really good idea. cool thanks for your input to get this merged and be compatible... :)

2021-02-01 19:30 UTC, merged

2021-02-01 19:30 UTC, botto commented
Thank you @xsteadfastx !